## Tensorflow Docs - Introduction to ML with TF
Here, I have documented my leaerning outcomes from the youtube videos of Tensorflow. I could not find better and perfect documentation which I can grasp quickly as per my understanding so that is why I am documenting my learning outcomes so someone else may get something out of it.

This is the Introduction video to the Tensorflow with machine learning. 

Intro to Machine Learning (ML Zero to Hero - Part 1)(https://www.youtube.com/watch?v=KNAWp2S3w94)

## Code Flow
* Install tensorflow if you do not have it in your environment
* Import tensorflow
* create a basic model (Which in this case is Seauential model)
* create your own data
* feed the model the data
* train the model
* Predict the unknown value

In [ ]:
!pip install tensorflow

     |███████████████████████████▎    | 273.4 MB 110.1 MB/s eta 0:00:01IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

     |████████████████████████████████| 320.4 MB 26 kB/s 
     |████████████████████████████████| 42 kB 3.7 MB/s 
     |████████████████████████████████| 10.6 MB 78.3 MB/s 
     |████████████████████████████████| 1.0 MB 102.2 MB/s 
     |████████████████████████████████| 20.1 MB 46.2 MB/s 
     |████████████████████████████████| 57 kB 13.3 MB/s 
     |████████████████████████████████| 127 kB 62.2 MB/s 
     |████████████████████████████████| 3.8 MB 36.5 MB/s 
     |████████████████████████████████| 2.9 MB 61.3 MB/s 
     |████████████████████████████████| 459 kB 111.7 MB/s 
     |██████████████

In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [ ]:
xs = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
ys = np.array([-2.0, 1.0, 4.0, 7.0, 10.0, 13.0], dtype=float)


In [ ]:
model = keras.Sequential([keras.layers.Dense(units=1, input_shape=[1]])
model.compile(optimizer='sgd', loss='mean_squared_error')

SyntaxError: invalid syntax (<ipython-input-47-60f370549afc>, line 1)

In [ ]:
model.fit(x,y,epochs=500)

4/4 [==============================] - 0s 629us/step - loss: nan
Epoch 2/500
4/4 [==============================] - 0s 604us/step - loss: nan
Epoch 3/500
4/4 [==============================] - 0s 632us/step - loss: nan
Epoch 4/500
4/4 [==============================] - 0s 616us/step - loss: nan
Epoch 5/500
4/4 [==============================] - 0s 694us/step - loss: nan
Epoch 6/500
4/4 [==============================] - 0s 551us/step - loss: nan
Epoch 7/500
4/4 [==============================] - 0s 726us/step - loss: nan
Epoch 8/500
4/4 [==============================] - 0s 593us/step - loss: nan
Epoch 9/500
4/4 [==============================] - 0s 637us/step - loss: nan
Epoch 10/500
4/4 [==============================] - 0s 677us/step - loss: nan
Epoch 11/500
4/4 [==============================] - 0s 618us/step - loss: nan
Epoch 12/500
4/4 [==============================] - 0s 627us/step - loss: nan
Epoch 13/500
4/4 [==============================] - 0s 2ms/step - loss: nan
Epoch 14/

In [ ]:
xi=model.predict([-90])
print(xi)


[[nan]]


In [ ]:
model.predict([-900000000000000])

array([[nan]], dtype=float32)

In [ ]:
model.predict([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0])

array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan]], dtype=float32)

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

model1 = keras.Sequential(
    [
        layers.Dense(units = 1, input_shape=[1],  name="layer1"),
    
        
    ]
)

In [ ]:
model1.compile(optimizer='sgd', loss='mean_squared_error')

In [ ]:
model1.fit(x,y, epochs=50)

Epoch 1/50
4/4 [==============================] - 0s 980us/step - loss: 690663932704063488.0000
Epoch 2/50
4/4 [==============================] - 0s 828us/step - loss: 91278319213701013774579013779456.0000
Epoch 3/50
4/4 [==============================] - 0s 764us/step - loss: inf                                 
Epoch 4/50
4/4 [==============================] - 0s 563us/step - loss: inf
Epoch 5/50
4/4 [==============================] - 0s 753us/step - loss: inf
Epoch 6/50
4/4 [==============================] - 0s 573us/step - loss: nan
Epoch 7/50
4/4 [==============================] - 0s 644us/step - loss: nan
Epoch 8/50
4/4 [==============================] - 0s 603us/step - loss: nan
Epoch 9/50
4/4 [==============================] - 0s 607us/step - loss: nan
Epoch 10/50
4/4 [==============================] - 0s 654us/step - loss: nan
Epoch 11/50
4/4 [==============================] - 0s 620us/step - loss: nan
Epoch 12/50
4/4 [==============================] - 0s 685us/step - loss: na

In [ ]:
model1.predict([-1,0,1,2,3,4,5])

array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan]], dtype=float32)

In [ ]:
x = list(range(0, 101))

In [ ]:
x[32]

32

In [ ]:
y = []
for i in x:
    y.append((4*i*i) - 3)

In [ ]:
y

[-3,
 1,
 13,
 33,
 61,
 97,
 141,
 193,
 253,
 321,
 397,
 481,
 573,
 673,
 781,
 897,
 1021,
 1153,
 1293,
 1441,
 1597,
 1761,
 1933,
 2113,
 2301,
 2497,
 2701,
 2913,
 3133,
 3361,
 3597,
 3841,
 4093,
 4353,
 4621,
 4897,
 5181,
 5473,
 5773,
 6081,
 6397,
 6721,
 7053,
 7393,
 7741,
 8097,
 8461,
 8833,
 9213,
 9601,
 9997,
 10401,
 10813,
 11233,
 11661,
 12097,
 12541,
 12993,
 13453,
 13921,
 14397,
 14881,
 15373,
 15873,
 16381,
 16897,
 17421,
 17953,
 18493,
 19041,
 19597,
 20161,
 20733,
 21313,
 21901,
 22497,
 23101,
 23713,
 24333,
 24961,
 25597,
 26241,
 26893,
 27553,
 28221,
 28897,
 29581,
 30273,
 30973,
 31681,
 32397,
 33121,
 33853,
 34593,
 35341,
 36097,
 36861,
 37633,
 38413,
 39201,
 39997]

In [ ]:
x

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

In [ ]:
y

[-3,
 1,
 13,
 33,
 61,
 97,
 141,
 193,
 253,
 321,
 397,
 481,
 573,
 673,
 781,
 897,
 1021,
 1153,
 1293,
 1441,
 1597,
 1761,
 1933,
 2113,
 2301,
 2497,
 2701,
 2913,
 3133,
 3361,
 3597,
 3841,
 4093,
 4353,
 4621,
 4897,
 5181,
 5473,
 5773,
 6081,
 6397,
 6721,
 7053,
 7393,
 7741,
 8097,
 8461,
 8833,
 9213,
 9601,
 9997,
 10401,
 10813,
 11233,
 11661,
 12097,
 12541,
 12993,
 13453,
 13921,
 14397,
 14881,
 15373,
 15873,
 16381,
 16897,
 17421,
 17953,
 18493,
 19041,
 19597,
 20161,
 20733,
 21313,
 21901,
 22497,
 23101,
 23713,
 24333,
 24961,
 25597,
 26241,
 26893,
 27553,
 28221,
 28897,
 29581,
 30273,
 30973,
 31681,
 32397,
 33121,
 33853,
 34593,
 35341,
 36097,
 36861,
 37633,
 38413,
 39201,
 39997]

In [ ]:
x = np.array(x, dtype=float)
y = np.array(y, dtype=float)